# Generated by Django 5.1.5 on 2025-01-16 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaDiem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_dia_diem', models.CharField(max_length=255)),
                ('dia_chi', models.CharField(max_length=255)),
                ('suc_chua', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SuKien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_su_kien', models.CharField(max_length=255)),
                ('mo_ta', models.TextField()),
                ('thoi_gian_bat_dau', models.DateTimeField()),
                ('thoi_gian_ket_thuc', models.DateTimeField()),
                ('dia_diem', models.CharField(max_length=255)),
                ('gia_ve', models.DecimalField(decimal_places=2, max_digits=10)),
                ('so_luong_ve', models.PositiveIntegerField()),
                ('nguoi_tao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='su_kien', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_sponsor', models.CharField(max_length=255)),
                ('mo_ta', models.TextField()),
                ('thong_tin_gian_hang', models.TextField()),
                ('su_kien', models.ManyToManyField(related_name='sponsors', to='app.sukien')),
            ],
        ),
        migrations.CreateModel(
            name='NguoiThamGia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_tham_gia', models.DateTimeField(auto_now_add=True)),
                ('email_da_gui', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('su_kien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nguoi_tham_gia', to='app.sukien')),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mo_ta', models.TextField()),
                ('ngay_gui', models.DateTimeField(auto_now_add=True)),
                ('da_gui', models.BooleanField(default=False)),
                ('su_kien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='app.sukien')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phan_hoi', models.TextField()),
                ('nguoi_tham_gia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='app.nguoithamgia')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='app.survey')),
            ],
        ),
        migrations.CreateModel(
            name='Ve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_ve', models.CharField(max_length=255)),
                ('loai_ve', models.CharField(max_length=255)),
                ('gia_ve', models.DecimalField(decimal_places=2, max_digits=10)),
                ('so_luong', models.PositiveIntegerField()),
                ('su_kien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ves', to='app.sukien')),
            ],
        ),
    ]
