# Generated by Django 5.1.5 on 2025-02-12 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_sukien_image_nguoithamgia_qr_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nguoithamgia',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='nguoithamgia',
            name='phuong_thuc_thanh_toan',
            field=models.CharField(choices=[('cash', 'Tiền mặt'), ('card', 'Thẻ tín dụng'), ('online', 'Thanh toán trực tuyến')], default='cash', max_length=20),
        ),
        migrations.AddField(
            model_name='nguoithamgia',
            name='so_dien_thoai',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='nguoithamgia',
            name='ten',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ve',
            name='ngay_bat_dau_ban_ve',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ve',
            name='ngay_ket_thuc_ban_ve',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ve',
            name='so_luong_da_ban',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
